#!/bin/bash

VERSION="0.0.1"
VOLUME_NAME=$1
SMB_HOST=$2
SMB_PATH=$3
SMB_USER=$4
SMB_PASS=$5
SMBOPT_UID=$6
SMBOPT_GID=$7
SMBOPT_FILEMODE=$8
SMBOPT_DIRMODE=$9

# Function to check for updates and update the script
check_for_updates() {
    local version_url="https://raw.githubusercontent.com/fsteltenkamp/DockerScripts/main/dvsmbcr.ver"
    local url="https://raw.githubusercontent.com/fsteltenkamp/DockerScripts/main/dvsmbcr"
    local tmp_file="/tmp/dvsmbcr_new"

    # Check if the content of $version_url is different to our $VERSION var:
    if [ "$(curl -s $version_url)" != "$VERSION" ]; then
        echo "A new version of the script is available. Updating..."
        curl -s -o "$tmp_file" "$url"
        mv "$tmp_file" "$0"
        chmod +x "$0"
        echo "Update complete. Please re-run the script. (arrow-up + enter)"
        exit 0
    fi
}

usage() {
    echo "Usage: $0 <volume_name> <smb_host> <smb_path> <smb_user> <smb_pass> [smbopt_uid] [smbopt_gid] [smbopt_filemode] [smbopt_dirmode]"
    echo "Example: $0 myvolume 192.168.178.1 share myuser mypass 1000 1000 0644 0755"
}

check_arguments() {
    if [ -z "$VOLUME_NAME" ] || [ -z "$SMB_HOST" ] || [ -z "$SMB_PATH" ] || [ -z "$SMB_USER" ] || [ -z "$SMB_PASS" ]; then
        echo "Error: Missing arguments"
        usage
        exit 1
    fi
}

# check docker volume
check_volume() {
    volume_inspect=$(docker volume inspect "$VOLUME_NAME")
    # if the volume exists, prompt user to remove it (supply command)
    if [ $? -eq 0 ]; then
        echo "Volume $VOLUME_NAME already exists. Please remove it first."
        echo "Use this: docker volume rm $VOLUME_NAME"
        exit 1
    fi
}

# Create the volume
create_volume() {
    local OPTSTRING="o=addr=$SMB_HOST,username=$SMB_USER,password=$SMB_PASS"
    # only use the smbopt_* variables if they are set
    if [ -n "$SMBOPT_UID" ]; then
        OPTSTRING="$OPTSTRING,uid=$SMBOPT_UID"
    fi
    if [ -n "$SMBOPT_GID" ]; then
        OPTSTRING="$OPTSTRING,gid=$SMBOPT_GID"
    fi
    if [ -n "$SMBOPT_FILEMODE" ]; then
        OPTSTRING="$OPTSTRING,filemode=$SMBOPT_FILEMODE"
    fi
    if [ -n "$SMBOPT_DIRMODE" ]; then
        OPTSTRING="$OPTSTRING,dirmode=$SMBOPT_DIRMODE"
    fi
    docker volume create \
            --driver local \
            --opt type=cifs \
            --opt device=//$SMB_HOST/$SMB_PATH \
            --opt $OPTSTRING \
            --name $VOLUME_NAME
}

## Main
check_for_updates
check_arguments
check_volume
create_volume