#!/bin/bash

VERSION="1.0"
VOLUME_NAME=$1
SMB_HOST=$2
SMB_PATH=$3
SMB_USER=$4
SMB_PASS=$5
SMBOPT_UID=$6
SMBOPT_GID=$7
SMBOPT_FILEMODE=$8
SMBOPT_DIRMODE=$9

# Function to check for updates and update the script
check_for_updates() {
    local version_url="https://raw.githubusercontent.com/fsteltenkamp/DockerScripts/main/dvsmbcr.ver"
    local url="https://raw.githubusercontent.com/fsteltenkamp/DockerScripts/main/dvsmbcr"
    local tmp_file="/tmp/dvsmbcr_new"

    # Check if the content of $version_url is different to our $VERSION var:
    local REMOTE_VERSION=$(curl -s $version_url) # catch curl errors:
    if [ $? -ne 0 ]; then
        echo "Error: Could not check for updates."
        return
    fi
    if [ "$REMOTE_VERSION" != "$VERSION" ]; then
        echo "A new version of the script is available. Updating..."
        curl -s -o "$tmp_file" "$url"
        mv "$tmp_file" "$0"
        chmod +x "$0"
        echo "Update complete. Please re-run the script. (arrow-up + enter)"
        exit 0
    fi
}

usage() {
    echo "Usage: $0 <volume_name> <smb_host> <smb_path> <smb_user> <smb_pass> [smbopt_uid] [smbopt_gid] [smbopt_filemode] [smbopt_dirmode]"
    echo "Example: $0 myvolume 192.168.178.1 share myuser mypass 1000 1000 0644 0755"
}

check_arguments() {
    if [ -z "$VOLUME_NAME" ] || [ -z "$SMB_HOST" ] || [ -z "$SMB_PATH" ] || [ -z "$SMB_USER" ] || [ -z "$SMB_PASS" ]; then
        echo "Error: Missing arguments"
        usage
        exit 1
    fi
}

# check docker volume
check_volume() {
    volume_inspect=$(docker volume inspect "$VOLUME_NAME" 2> /dev/null)
    # if the volume exists, prompt user to remove it (supply command)
    if [ $? -eq 0 ]; then
        echo "Volume $VOLUME_NAME already exists. Please remove it first."
        echo "Use this: docker volume rm $VOLUME_NAME"
        exit 1
    fi
}

# Create the volume
create_volume() {
    local OPTSTRING="o=username=$SMB_USER,password=$SMB_PASS"
    # only use the smbopt_* variables if they are set
    if [ -n "$SMBOPT_UID" ]; then
        OPTSTRING="$OPTSTRING,uid=$SMBOPT_UID"
    fi
    if [ -n "$SMBOPT_GID" ]; then
        OPTSTRING="$OPTSTRING,gid=$SMBOPT_GID"
    fi
    if [ -n "$SMBOPT_FILEMODE" ]; then
        OPTSTRING="$OPTSTRING,filemode=$SMBOPT_FILEMODE"
    fi
    if [ -n "$SMBOPT_DIRMODE" ]; then
        OPTSTRING="$OPTSTRING,dirmode=$SMBOPT_DIRMODE"
    fi
    docker volume create \
            --driver local \
            --opt type=cifs \
            --opt device=//$SMB_HOST/$SMB_PATH \
            --opt $OPTSTRING \
            --name $VOLUME_NAME
}

install_other_scripts() {
    # request permission:
    echo "This action will install several more scripts on this system to aid in handling docker volumes."
    echo "The Scripts will be installed in /usr/local/bin."
    echo "Do you want to continue? (y/n)"
    read -r answer
    # only continue if user gives permission:
    if [ "$answer" == "y" ]; then
        # download the scripts:
        curl -s -o /usr/local/bin/dvbr https://raw.githubusercontent.com/fsteltenkamp/DockerScripts/main/dvbr
        curl -s -o /usr/local/bin/dvls https://raw.githubusercontent.com/fsteltenkamp/DockerScripts/main/dvls
        curl -s -o /usr/local/bin/dvfbr https://raw.githubusercontent.com/fsteltenkamp/DockerScripts/main/dvfbr
        curl -s -o /usr/local/bin/dvsh https://raw.githubusercontent.com/fsteltenkamp/DockerScripts/main/dvsh
        curl -s -o /usr/local/bin/dvsmbcr https://raw.githubusercontent.com/fsteltenkamp/DockerScripts/main/dvsmbcr
        # make them executable:
        chmod +x /usr/local/bin/dvbr
        chmod +x /usr/local/bin/dvfbr
        chmod +x /usr/local/bin/dvls
        chmod +x /usr/local/bin/dvsh
        chmod +x /usr/local/bin/dvsmbcr
        echo "Scripts installed. You can now use the following scripts:"
        echo "- dvbr.....backup and restore Docker Volumes."
        echo "- dvls.....list files inside a Docker Volume."
        echo "- dvfbr....start a filebrowser to manage files in a Docker Volume."
        echo "- dvsh.....start a shell inside a Docker Volume."
        echo "- dvsmbcr..easily create a new Volume that is connected to a SMB Share."
    fi
}

# MAIN
# check if the user wants to install the other scripts:
if [[ "$@" == *"--install"* ]]; then
    install_other_scripts
    exit
fi
# check if the user wants to update the script:
if [[ "$@" == *"--update"* ]]; then
    check_for_updates
    exit
fi

check_arguments
check_volume
create_volume